# Generated by Django 3.2.1 on 2021-06-29 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 13, 50, 50, 721839, tzinfo=utc)),
        ),
    ]
