# Generated by Django 3.2.1 on 2021-06-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donor_lastdonateddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='lastdonateddate',
        ),
    ]
