# Generated by Django 3.2.5 on 2021-07-06 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 15, 2, 20, 195463, tzinfo=utc)),
        ),
    ]
