# Generated by Django 3.2.1 on 2021-06-29 13:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.donor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 13, 19, 28, 555635, tzinfo=utc)),
        ),
    ]
