# Generated by Django 3.2.5 on 2021-07-07 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_alter_history_lastdonateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 7, 7, 15, 1, 24, 121898, tzinfo=utc)),
        ),
    ]
