# Generated by Django 3.2.1 on 2021-06-29 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('record', '0003_alter_history_lastdonateddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='name',
        ),
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 13, 38, 29, 569584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.donor'),
        ),
    ]
