# Generated by Django 3.2.1 on 2021-06-29 13:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20210629_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 13, 50, 50, 722664, tzinfo=utc)),
        ),
    ]
