# Generated by Django 3.2.1 on 2021-06-29 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_alter_history_lastdonateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 6, 29, 13, 53, 17, 271085, tzinfo=utc)),
        ),
    ]
