# Generated by Django 3.2.1 on 2021-07-03 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_alter_history_lastdonateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 7, 3, 9, 25, 27, 954164, tzinfo=utc)),
        ),
    ]
