# Generated by Django 3.2.1 on 2021-07-06 08:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_alter_history_lastdonateddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastdonateddate',
            field=models.DateField(default=datetime.datetime(2021, 7, 6, 8, 52, 42, 830095, tzinfo=utc)),
        ),
    ]
